#!/usr/bin/env bash
# GENERATED from governance canonical/agent-surfaces/ by scripts/gen-agent-surfaces.sh (ADR-0037).
# Do not edit this file. Edit the canonical source and regenerate; CI fails on drift.
# Fitness function: the ceremony tier a PR declares must match what its diff actually does.
# SPEC-0012, under ADR-0037 decision 7 and ADR-0028.
#
# WHY THIS EXISTS: AGDD applies one weight of ceremony to every change, so a comment typo nominally
# needs an approved spec. Nobody pays that, they skip — and the skipping is undocumented, which makes
# an exception indistinguishable from a violation after the fact. Tiers make the lighter path
# explicit and checkable instead of tacit.
#
# The tier is DECLARED, not inferred. Inferring it from the diff would make this check circular: it
# would only ever agree with itself. A human or agent writes `Ceremony: quick` in the PR body and
# this asserts the diff is entitled to it.
#
# Two properties do the safety work:
#   * No tier crosses the security floor. A diff touching authorization, tenant scoping, RLS, audit,
#     the agent wire, secrets, policies/, contracts/ or CI config takes `full` whatever its size. The
#     pattern list below is deliberately over-broad — a false positive costs a spec nobody needed, a
#     false negative costs an invariant.
#   * Absence never grants a waiver. No `Ceremony:` line means `full`, so the safe tier is the one
#     you get by doing nothing at all.
#
# Tested by governance/scripts/test-ceremony-tier.sh, one case per SPEC-0012 acceptance criterion.
#
# Inputs:
#   PR_BODY         the pull request body (CI passes github.event.pull_request.body)
#   PR_BODY_FILE    alternative: a file holding it, for local runs and tests
#   CEREMONY_BASE   base ref to diff against (default: origin/main)
#
# Exit: 0 the declared tier holds · 1 it does not · 3 the diff could not be determined
set -euo pipefail

# Submodule-boundary detection lives next door, shared with the dispatch hook (SPEC-0013 AC8).
_lib="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/lib-submodule-scope.sh"
[ -f "$_lib" ] || { echo "ceremony: missing $_lib" >&2; exit 3; }
# shellcheck source=/dev/null
. "$_lib"

base=${CEREMONY_BASE:-origin/main}

body=${PR_BODY:-}
if [ -z "$body" ] && [ -n "${PR_BODY_FILE:-}" ]; then
  [ -f "$PR_BODY_FILE" ] || { echo "ceremony: PR_BODY_FILE does not exist: $PR_BODY_FILE" >&2; exit 3; }
  body=$(cat "$PR_BODY_FILE")
fi

# Absence is not a waiver — no declaration means full, which requires everything.
tier=full
declared=$(printf '%s\n' "$body" | sed -n 's/^[[:space:]]*Ceremony:[[:space:]]*\([A-Za-z]*\).*$/\1/p' | head -1)
case "$declared" in
  full|quick|bugfix) tier=$declared ;;
  '') ;;
  *) echo "ceremony: unknown tier '$declared' — use full, quick or bugfix" >&2; exit 1 ;;
esac

if [ "$tier" = "full" ]; then
  echo "ceremony: full — nothing waived, nothing to check"
  exit 0
fi

# A gate that cannot see the diff must fail, not pass. A shallow clone with no merge base is the
# usual cause, and the usual fix is fetch-depth: 0 — the same thing governance CI already needs for
# `buf breaking`.
if ! changed=$(git diff --name-only "${base}...HEAD" 2>&1); then
  echo "ceremony: cannot diff against '${base}' — is it fetched? (CI needs fetch-depth: 0)" >&2
  printf '  %s\n' "$changed" >&2
  exit 3
fi
if [ -z "$changed" ]; then
  echo "ceremony: no files changed against ${base} — refusing to certify an empty diff" >&2
  exit 3
fi

fail=0
report() { echo "CEREMONY VIOLATION: $1"; fail=1; }

# --- the floor no tier crosses ------------------------------------------------------------------
# Substring patterns, matched against the whole path. Over-broad on purpose.
SECURITY_PATTERNS='policies/|contracts/|\.github/workflows/|/pep/|/pdp/|policy|authz|tenant|rls|audit|secret|token|agent|isolation|sandbox|rbac'

while IFS= read -r f; do
  [ -n "$f" ] || continue
  if printf '%s' "$f" | grep -Eqi "$SECURITY_PATTERNS"; then
    report "$f is security-relevant, so this change takes 'full' regardless of size (declared '$tier')"
  fi
done <<<"$changed"

# --- per-tier rules -----------------------------------------------------------------------------
SOURCE_RE='\.(go|ts|tsx|js|jsx|astro|svelte|sql|rego|proto)$'
TEST_RE='(_test\.go|\.test\.(ts|tsx|js|jsx)|\.spec\.(ts|tsx|js|jsx)|(^|/)tests?/|\.bats$|_test\.sh$)'

case "$tier" in
  quick)
    # quick claims no observable behaviour change, so no non-test source file may move.
    while IFS= read -r f; do
      [ -n "$f" ] || continue
      printf '%s' "$f" | grep -Eq "$SOURCE_RE" || continue
      printf '%s' "$f" | grep -Eq "$TEST_RE" && continue
      report "$f is source, which 'quick' does not cover — use 'bugfix' if a defect drove it, else 'full'"
    done <<<"$changed"
    ;;

  bugfix)
    # The failing test IS the specification, so a bugfix without one has waived the spec for nothing.
    if ! printf '%s\n' "$changed" | grep -Eq "$TEST_RE"; then
      report "'bugfix' waives the spec because the failing test is the spec — this diff adds no test"
    fi

    # Only meaningful in the composition; a submodule's own diff cannot span two of them. The
    # detection is shared with the dispatch pre-commit hook (SPEC-0013) rather than copied.
    spanned=$(printf '%s\n' "$changed" | spanned_submodules)
    if [ "$(printf '%s\n' "$spanned" | grep -c .)" -gt 1 ]; then
      report "this diff spans $(printf '%s\n' "$spanned" | tr '\n' ' ')— invariant 23, one commit never spans two submodules"
    fi
    ;;
esac

if [ "$fail" -ne 0 ]; then
  echo
  echo "ceremony: declared '$tier', diff is not entitled to it — SPEC-0012"
  echo "  fix: raise the tier in the PR body ('Ceremony: full'), or narrow the diff."
  exit 1
fi

echo "ceremony: $tier — declaration holds against $(printf '%s\n' "$changed" | grep -c .) changed file(s)"
