#!/usr/bin/env bash
# GENERATED from governance canonical/agent-surfaces/ by scripts/gen-agent-surfaces.sh (ADR-0037).
# Do not edit this file. Edit the canonical source and regenerate; CI fails on drift.
# CI-side scope boundary. SPEC-0013, answering its open question 1.
#
# WHY THIS EXISTS ALONGSIDE THE HOOK: `git commit --no-verify` skips dispatch-pre-commit.sh and
# always will. The hook catches wandering out of scope mid-task, which is the common failure; this
# catches the case the hook cannot, because CI runs on what was pushed rather than on what the
# author chose to run.
#
# It cannot read the hook's scope. That lives at `git rev-parse --git-path dispatch-scope`, inside a
# worktree's gitdir, deliberately uncommittable (SPEC-0013 AC7) — so CI has no access to it and
# never will. The declaration therefore moves to the PR body, the same place the ceremony tier lives
# and for the same reason: it is what CI can actually read.
#
#   Scope: backend modules/policy/** **/*_test.go
#
# TWO CHECKS, AND ONLY ONE NEEDS A DECLARATION:
#
#   1. Invariant 23 — unconditional, every PR, declaration or not. This closes a real gap:
#      check-ceremony-tier.sh only reaches its submodule-span check inside the `bugfix` branch, so a
#      `Ceremony: full` PR spanning two submodules passed CI unchecked. A hard rule guarded only
#      when someone declares the lighter tier is a rule guarded backwards.
#
#   2. Path scope — only when a `Scope:` line is present. Absent it, this half is inert and says so,
#      because an unscoped PR and an unchecked one must not look alike in a log.
#
# Inputs:
#   PR_BODY       the pull request body (CI passes github.event.pull_request.body)
#   PR_BODY_FILE  alternative: a file holding it, for local runs and tests
#   SCOPE_BASE    base ref to diff against (default: origin/main)
#
# Exit: 0 clean · 1 violation · 3 the diff could not be determined
set -euo pipefail

_here="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
for _lib in lib-submodule-scope.sh lib-pr-declaration.sh; do
  [ -f "$_here/$_lib" ] || { echo "dispatch-scope: missing $_here/$_lib" >&2; exit 3; }
  # shellcheck source=/dev/null
  . "$_here/$_lib"
done

base=${SCOPE_BASE:-origin/main}

body=${PR_BODY:-}
if [ -z "$body" ] && [ -n "${PR_BODY_FILE:-}" ]; then
  [ -f "$PR_BODY_FILE" ] || { echo "dispatch-scope: PR_BODY_FILE does not exist: $PR_BODY_FILE" >&2; exit 3; }
  body=$(cat "$PR_BODY_FILE")
fi

# Same reasoning as the ceremony gate: a check that cannot see the diff fails rather than passes.
if ! changed=$(git diff --name-only "${base}...HEAD" 2>&1); then
  echo "dispatch-scope: cannot diff against '${base}' — is it fetched? (CI needs fetch-depth: 0)" >&2
  printf '  %s\n' "$changed" >&2
  exit 3
fi
if [ -z "$changed" ]; then
  echo "dispatch-scope: no files changed against ${base} — nothing to check"
  exit 0
fi

fail=0
report() { echo "DISPATCH SCOPE VIOLATION: $1"; fail=1; }

# --- 1. invariant 23, unconditionally -----------------------------------------------------------
spanned=$(printf '%s\n' "$changed" | spanned_submodules)
if [ "$(printf '%s\n' "$spanned" | grep -c .)" -gt 1 ]; then
  report "this diff spans $(printf '%s\n' "$spanned" | tr '\n' ' ')— invariant 23, one commit never spans two submodules"
  echo "          split it: governance PR first, then each consumer, then the super-repo pin bump (ADR-0027)"
fi

# --- 2. declared path scope, when present -------------------------------------------------------
# Not a plain grep: a PR body documents this syntax, and the example must not be mistaken for the
# declaration. See lib-pr-declaration.sh — this exact gate once enforced a scope it had copied out
# of its own explanatory text.
declared=$(printf '%s\n' "$body" | pr_declaration Scope)

if [ -z "$declared" ]; then
  echo "dispatch-scope: no Scope declared — invariant 23 checked, path scope not"
else
  want_repo=${declared%% *}
  want_paths=${declared#* }
  if [ "$want_repo" = "$want_paths" ]; then
    echo "dispatch-scope: 'Scope: $declared' needs a repo and at least one glob" >&2
    exit 1
  fi

  # In the composition the declared repo must be the one the diff touches. Inside a submodule there
  # is nothing to compare it against, so the name is documentation there rather than a constraint.
  if [ -f .gitmodules ] && [ -n "$spanned" ]; then
    if ! printf '%s\n' "$spanned" | grep -qx "$want_repo"; then
      report "declared repo '$want_repo' but the diff touches $(printf '%s\n' "$spanned" | tr '\n' ' ')"
    fi
  fi

  while IFS= read -r f; do
    [ -n "$f" ] || continue

    # Globs are submodule-relative, because that is what the pre-commit hook sees: it runs inside
    # the submodule. In the composition the diff carries a `backend/` prefix that the hook never
    # encounters, so strip it before matching — otherwise the same declaration would mean two
    # different things depending on which side checked it, which is worse than not checking.
    rel=$f
    case "$f" in "$want_repo"/*) rel=${f#"$want_repo"/} ;; esac

    matched=0
    # `set -f` is load-bearing. Unquoted $want_paths needs word-splitting — the list is
    # space-separated — but WITHOUT it bash also does pathname expansion, so a glob like `.github/**`
    # is replaced by whatever files happen to exist before it is ever used as a pattern. That is not
    # theoretical: it is how this check rejected `.github/workflows/ci.yml` against a scope that
    # plainly covered it, and why the first version's tests passed by coincidence — their fixtures
    # expanded to exactly the file being tested.
    set -f
    # shellcheck disable=SC2086
    for glob in $want_paths; do
      # shellcheck disable=SC2254
      case "$rel" in $glob) matched=1; break ;; esac
    done
    set +f
    [ "$matched" -eq 1 ] || report "$f is outside the declared scope: $want_paths"
  done <<<"$changed"
fi

if [ "$fail" -ne 0 ]; then
  echo
  echo "dispatch-scope: the pushed diff does not match what was declared — SPEC-0013"
  echo "  This runs in CI precisely because --no-verify skips the pre-commit hook."
  echo "  Fix the diff, or widen the 'Scope:' line in the PR body deliberately."
  exit 1
fi

echo "dispatch-scope: ok — $(printf '%s\n' "$changed" | grep -c .) changed file(s)"
