#!/usr/bin/env bash
# webfrontend fitness function: the frontend talks to the BFF over HTTP and to nothing else.
#
# Invariant 22 — webfrontend -> bff -> backend -> governance(contracts), one way. The frontend never
# reaches backend directly, and it never links another repo's source: the only things it holds are
# generated types under src/gen (from governance/contracts, via buf) and HTTP calls to the BFF.
# ADR-0025/0015 add the other half: SSR is a thin proxy, so data access and business logic live
# behind the BFF, not here. The super-repo's check-dep-direction.sh enforces the Go side of the same
# rule; this is the TypeScript side, which that scan cannot see.
#
# Any hit fails CI.
set -euo pipefail
cd "$(dirname "$0")/.."

fail=0
report() { echo "BOUNDARY VIOLATION: $1"; fail=1; }

# Match import/export specifiers and require() calls only — not comments, strings or identifiers that
# merely contain the word. A bare specifier or a relative path escaping the repo both count.
spec_re() { # spec_re <module>
  printf '(from|import|require)[[:space:]]*\(?[[:space:]]*["'\''"]%s(/|["'\''"])' "$1"
}

scan() { # scan <label> <module-spec...>
  local label="$1"; shift

  local files=()
  while IFS= read -r -d '' f; do
    files+=("$f")
  done < <(find src tests -type f \
    \( -name '*.ts' -o -name '*.tsx' -o -name '*.astro' -o -name '*.js' -o -name '*.mjs' \) \
    -not -path 'src/gen/*' -print0 2>/dev/null)
  [ ${#files[@]} -gt 0 ] || return 0

  local m re hits
  for m in "$@"; do
    re=$(spec_re "$m")
    if hits=$(grep -InE "$re" "${files[@]}" 2>/dev/null); then
      report "$label — $m"
      printf '    %s\n' "$hits"
    fi
  done
}

# Another repo's source. webfrontend consumes generated types and the BFF's HTTP surface, nothing else.
scan "imports another repo's source (invariant 22)" \
  '@gitfrok/backend' '@gitfrok/bff' '\.\./\.\./backend' '\.\./\.\./bff'

# Infrastructure clients. If the frontend can open a database or a broker connection, the BFF has
# stopped being the only door (invariant 15/18, ADR-0025).
scan "reaches infrastructure directly — that belongs behind the BFF" \
  'pg' 'pg-promise' 'postgres' 'kafkajs' 'ioredis' 'redis' '@opa/opa'

# src/gen is generated (buf, from governance/contracts). Hand-editing it makes the next codegen run
# silently revert the change, so the tree must only ever contain generated files.
if [ -d src/gen ]; then
  while IFS= read -r -d '' f; do
    grep -q 'generated by protoc-gen-es' "$f" || report "src/gen file is not generated output: $f"
  done < <(find src/gen -type f -name '*.ts' -print0 2>/dev/null)
fi

if [ "$fail" -ne 0 ]; then
  echo "boundaries: FAIL"
  exit 1
fi
echo "boundaries: OK"
