#!/usr/bin/env bash
# GENERATED from governance canonical/agent-surfaces/ by scripts/gen-agent-surfaces.sh (ADR-0037).
# Do not edit this file. Edit the canonical source and regenerate; CI fails on drift.
# Shell portability gate. SPEC-0014, closing T-0003 AC4.
#
# WHY THIS EXISTS: AC4 promises "works on macOS and Linux" and its macOS half had never run on
# macOS. What stood in for it was a bash:3.2 container — Alpine plus busybox, no lineage to Darwin —
# and a grep somebody remembered to run. That grep found two genuinely macOS-fatal defects, and then
# went eleven scripts stale inside a month. This is that audit, promoted to something that cannot go
# stale, and pointed at a real BSD userland.
#
# THREE PARTS, AND THE THIRD IS WHAT MAKES THE FIRST TWO MEAN ANYTHING:
#
#   1. Parse   — every tracked *.sh under the system bash, by absolute path.
#   2. Audit   — every tracked *.sh against portability-flags.tsv, the one codified list.
#   3. Assert  — refuse to report success unless the bash and the userland are what we claim.
#
# Part 3 is not ceremony. Hosted macOS runners ship Homebrew, and GNU coreutils ahead of /usr/bin
# would quietly turn this whole gate into a second Linux lane printing "macOS: OK" forever. That is
# the exact defect shape this task keeps recording: a check that silently consults something other
# than what it appears to. So the assertions are hard failures, never skips — including the bash
# version, because if Apple ever ships something other than 3.2 that is a fact to re-reason about,
# not to drift past.
#
# ON LINUX the userland assertion is meaningless rather than optional, so it does not run and the
# gate says so on its own output line. Parse and audit still run, so a contributor with no Mac gets
# the flag audit locally (SPEC-0014 AC8).
#
# Inputs (all optional; they exist so the negative controls in test-shell-portability.sh can force
# each failure mode rather than trust that it would fire):
#   PORTABILITY_STRICT   1 forces the part-3 assertions on any OS; 0 forces them off
#   PORTABILITY_BASH     the bash to parse with, overriding the per-OS default
#   PORTABILITY_FLAGS    path to the pattern list, overriding the sibling portability-flags.tsv
#
# Exit: 0 clean · 1 violation · 3 the environment could not be established
set -euo pipefail

_here="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
flags=${PORTABILITY_FLAGS:-$_here/portability-flags.tsv}
[ -f "$flags" ] || { echo "portability: missing pattern list: $flags" >&2; exit 3; }

os=$(uname -s)
if [ -n "${PORTABILITY_STRICT:-}" ]; then
  strict=$PORTABILITY_STRICT
elif [ "$os" = "Darwin" ]; then
  strict=1
else
  strict=0
fi

if [ -n "${PORTABILITY_BASH:-}" ]; then
  parse_bash=$PORTABILITY_BASH
elif [ "$os" = "Darwin" ]; then
  # Absolute, never `command -v bash`. On a runner with Homebrew's bash 5 first on PATH, parsing
  # with the PATH bash would test the one platform this gate is not about.
  parse_bash=/bin/bash
else
  parse_bash=$(command -v bash || true)
fi

[ -n "$parse_bash" ] && [ -x "$parse_bash" ] || {
  echo "portability: no usable bash at '${parse_bash:-<unset>}'" >&2; exit 3; }

fail=0
report() { echo "PORTABILITY VIOLATION: $1"; fail=1; }

# THE ONE ESCAPE HATCH, and it exists because the first real run of this gate earned it. The list
# below is a proxy: "mentions a GNU flag" stands in for "will break on BSD". The proxy is wrong in
# one specific, legitimate shape — a GNU construct *probed* inside a conditional with a portable
# fallback behind it, which is what a careful author writes and is strictly better than either arm
# alone. bench-storage.sh's fstype detector is exactly that, and it is that shape *because* the
# previous audit made it so; a gate that condemned it would be punishing the fix it exists to cause.
#
#   stat -f -c %T "$path"   # portability-ok: GNU probe, df+mount fallback below
#
# Narrow on purpose: the marker binds to one line (or the comment line directly above it), it must
# carry a reason, and every waiver is PRINTED on every run and counted in the summary. A waiver you
# cannot see in the log is an exemption; one you cannot avoid reading is a declaration.
waiver_for() { # waiver_for <file> <line> -> prints the reason, empty if none
  sed -n "$(( $2 > 1 ? $2 - 1 : $2 ))p;$2p" "$1" \
    | sed -n 's/.*portability-ok:[[:space:]]*\([^ ].*\)$/\1/p' | head -1
}

# --- 3. environment assertion (runs first: it decides what the other two are worth) --------------

bash_version_line=$("$parse_bash" --version 2>/dev/null | head -1 || true)
[ -n "$bash_version_line" ] || { echo "portability: '$parse_bash' did not report a version" >&2; exit 3; }
echo "portability: parsing with $parse_bash — $bash_version_line"

# A GNU tool answers --version with 0 and says so on its first line. Every BSD one exits non-zero
# with a usage error, so "succeeded and said GNU" is the discriminator rather than any version
# string — which also means a tool that stops printing its provenance fails closed, not open.
is_gnu() {
  _out=$("$1" --version 2>/dev/null) || return 1
  printf '%s\n' "$_out" | head -1 | grep -qi 'GNU' || return 1
  return 0
}

if [ "$strict" = "1" ]; then
  case "$bash_version_line" in
    *"version 3.2"*) : ;;
    *) report "parsed with a bash that is not 3.2 — macOS ships 3.2.57 and this gate is worthless against anything newer"
       echo "          got: $bash_version_line" ;;
  esac

  for tool in find stat sed readlink date; do
    resolved=$(command -v "$tool" || true)
    if [ -z "$resolved" ]; then
      report "$tool is not on PATH at all"
      continue
    fi
    case "$resolved" in
      /usr/bin/"$tool"|/bin/"$tool") : ;;
      *) report "$tool resolves to $resolved, ahead of the system one — a shimmed PATH makes this gate a second Linux lane" ;;
    esac
    if is_gnu "$resolved"; then
      report "$tool at $resolved is the GNU implementation, not the BSD one"
    fi
  done

  if [ "$fail" -ne 0 ]; then
    echo
    echo "portability: the environment is not what this gate claims to test — SPEC-0014 part 3."
    echo "  Nothing below this line would have meant anything, so nothing below it ran."
    exit 1
  fi
  echo "portability: userland asserted BSD — find, stat, sed, readlink, date are the system ones"
else
  echo "portability: userland assertion not applicable on $os — it is a Darwin claim; parse and audit still bind"
fi

# --- 0. the scripts ------------------------------------------------------------------------------

# Read into an array rather than iterating an unquoted variable. `for f in $scripts` word-splits AND
# pathname-expands, so a script whose name contained a glob character would be silently replaced by
# whatever the filesystem happened to hold. That is not hypothetical prudence — it is SPEC-0013's
# defect 1, which passed twenty tests while live.
scripts=()
while IFS= read -r _f; do
  [ -n "$_f" ] || continue
  scripts[${#scripts[@]}]=$_f
done <<EOF
$(git ls-files '*.sh')
EOF

if [ ${#scripts[@]} -eq 0 ]; then
  echo "portability: no tracked *.sh in this repo — nothing to check"
  exit 0
fi

# Declared, never silently omitted (SPEC-0014 AC7). Excluded from EXECUTION by the CI job, never
# from parsing or auditing here — the split between macOS-parseable and macOS-runnable is one the
# record already had to draw, and burying it is how it gets lost. Only entries this repo actually
# holds are printed, since the same file is generated into all five.
echo "portability: not runnable on macOS, by declaration —"
declared_unrunnable=0
while IFS=$(printf '\t') read -r _path _reason; do
  case "$_path" in ''|'#'*) continue ;; esac
  for _s in "${scripts[@]}"; do
    if [ "$_s" = "$_path" ]; then
      echo "  $_path — $_reason"
      declared_unrunnable=$((declared_unrunnable + 1))
    fi
  done
done <<EOF
scripts/bench-git-workload.sh$(printf '\t')needs GNU date's %N; exits with a clear message without it
EOF
[ "$declared_unrunnable" -gt 0 ] || echo "  (none in this repo)"

# --- 1. parse ------------------------------------------------------------------------------------

for f in "${scripts[@]}"; do
  if ! err=$("$parse_bash" -n "$f" 2>&1); then
    report "$f does not parse under $bash_version_line"
    printf '  %s\n' "$err"
  fi
done

# --- 2. audit ------------------------------------------------------------------------------------

patterns=()
labels=()
whys=()
while IFS=$(printf '\t') read -r pattern label why; do
  case "$pattern" in ''|'#'*) continue ;; esac
  patterns[${#patterns[@]}]=$pattern
  labels[${#labels[@]}]=$label
  whys[${#whys[@]}]=$why
done < "$flags"

[ ${#patterns[@]} -gt 0 ] || { echo "portability: $flags declares no patterns" >&2; exit 3; }

waived=0
for f in "${scripts[@]}"; do
  # Whole-line comments only, and stripped once per file. Stripping from the first `#` on every line
  # would maim ${var#prefix} and every `case` arm containing one, and a mangled line is a line the
  # patterns can no longer match — a false negative, which is the direction that matters here.
  # Trailing inline comments are therefore still audited: a GNU flag mentioned in one is a finding,
  # because the alternative is a gate that can be silenced with a `#`.
  #
  # Substituted with an empty line rather than deleted, so grep -n still reports the line number the
  # file actually has.
  body=$(sed 's/^[[:space:]]*#.*$//' "$f")
  i=0
  while [ "$i" -lt ${#patterns[@]} ]; do
    hits=$(printf '%s\n' "$body" | grep -nE "${patterns[$i]}" || true)
    if [ -n "$hits" ]; then
      while IFS= read -r hit; do
        [ -n "$hit" ] || continue
        ln=${hit%%:*}
        if [ -n "$(waiver_for "$f" "$ln")" ]; then
          waived=$((waived + 1))
          echo "portability: waived $f:$ln (${labels[$i]}) — $(waiver_for "$f" "$ln")"
        else
          report "$f:$ln uses ${labels[$i]} — ${whys[$i]}"
        fi
      done <<EOF
$hits
EOF
    fi
    i=$((i + 1))
  done
done

if [ "$fail" -ne 0 ]; then
  echo
  echo "portability: this tree would not work on macOS — SPEC-0014, T-0003 AC4."
  echo "  Fix the construct. Do not add an exception: the list is the contract, and the two defects"
  echo "  it was built from were both invisible to review and fatal on Darwin."
  exit 1
fi

echo "portability: OK — ${#scripts[@]} script(s) parsed, ${#patterns[@]} pattern(s) audited, 0 findings, $waived waived"
