#!/usr/bin/env bash
# GENERATED from governance canonical/agent-surfaces/ by scripts/gen-agent-surfaces.sh (ADR-0037).
# Do not edit this file. Edit the canonical source and regenerate; CI fails on drift.
# Pre-commit scope boundary. SPEC-0013.
#
# Rejects a commit that stages files outside the scope its unit of work declared. Installed into a
# working tree by dispatch-worktree.sh, never automatically — a hook that appears without being
# asked for is a hook people disable.
#
# WHAT THIS IS NOT: protection against intent. `git commit --no-verify` skips it and always will.
# It catches the mistake of wandering out of scope mid-task, which is the common failure; CI is what
# catches the deliberate case. SPEC-0013 open question 1 leaves whether this belongs in CI too.
#
# Scope lives at `git rev-parse --git-path dispatch-scope` — inside the gitdir, so it can never be
# staged, and per-worktree, so two worktrees of the same repo hold different scopes.
#
#   repo:   backend
#   paths:  modules/policy/** internal/pep/** *_test.go
set -euo pipefail

scope=$(git rev-parse --git-path dispatch-scope)

# No declaration means inert — but say so. An uninstalled hook and a permitting hook must not look
# the same in a log, which is the same reason every other gate here hard-fails rather than skipping.
if [ ! -f "$scope" ]; then
  echo "dispatch-scope: no scope declared for this worktree — hook is inert"
  exit 0
fi

want_repo=$(sed -n 's/^repo:[[:space:]]*//p' "$scope" | head -1)
want_paths=$(sed -n 's/^paths:[[:space:]]*//p' "$scope" | head -1)

staged=$(git diff --cached --name-only --diff-filter=ACMRT)
if [ -z "$staged" ]; then
  exit 0
fi

fail=0
report() { echo "DISPATCH SCOPE VIOLATION: $1" >&2; fail=1; }

# --- invariant 23, via the shared detection (SPEC-0013 AC4) --------------------------------------
lib="$(git rev-parse --show-toplevel)/scripts/lib-submodule-scope.sh"
if [ -f "$lib" ]; then
  # shellcheck source=/dev/null
  . "$lib"
  spanned=$(printf '%s\n' "$staged" | spanned_submodules)
  if [ "$(printf '%s\n' "$spanned" | grep -c .)" -gt 1 ]; then
    report "staged files span $(printf '%s\n' "$spanned" | tr '\n' ' ')— invariant 23, one commit never spans two submodules"
  fi
fi

# --- the declared path scope --------------------------------------------------------------------
if [ -n "$want_paths" ]; then
  while IFS= read -r f; do
    [ -n "$f" ] || continue
    matched=0
    # Word-split on purpose: `paths` is a space-separated glob list, and each needs to be a pattern
    # rather than a literal.
    # shellcheck disable=SC2086
    for glob in $want_paths; do
      # shellcheck disable=SC2254
      case "$f" in $glob) matched=1; break ;; esac
    done
    [ "$matched" -eq 1 ] || report "$f is outside the declared scope: $want_paths"
  done <<<"$staged"
fi

if [ "$fail" -ne 0 ]; then
  {
    echo
    echo "declared scope — repo: ${want_repo:-<unset>}"
    echo "                paths: ${want_paths:-<unset>}"
    echo
    echo "If the scope is wrong, widen it deliberately:"
    echo "  \$EDITOR $scope"
    echo "Do not reach for --no-verify; the point of the scope is that it was declared before the work."
  } >&2
  exit 1
fi

echo "dispatch-scope: ok — $(printf '%s\n' "$staged" | grep -c .) staged file(s) within scope"
