# shellcheck shell=bash
# GENERATED from governance canonical/agent-surfaces/ by scripts/gen-agent-surfaces.sh (ADR-0037).
# Do not edit this file. Edit the canonical source and regenerate; CI fails on drift.
# Shared submodule-boundary detection. SPEC-0013 AC8, ADR-0027 invariant 23.
#
# Sourced, not executed. Two callers need the same answer to "which submodules does this set of paths
# touch": check-ceremony-tier.sh, deciding whether a bugfix-tier diff crosses a repo boundary, and
# dispatch-pre-commit.sh, deciding whether to let a commit exist at all. A second copy of this would
# be exactly the drift ADR-0037 exists to prevent, one level down.
#
# In a submodule this is inert by construction: there is no .gitmodules, so nothing is ever reported.
# That is correct rather than a limitation — a submodule's own diff cannot span two submodules, and
# the composition is the only place where it can.

# spanned_submodules <paths-on-stdin> — print each submodule path the input touches, one per line.
#
# Reads paths on stdin rather than taking them as arguments so a very large staged file list cannot
# hit ARG_MAX, and so callers can pipe `git diff --name-only` straight in.
spanned_submodules() {
    local paths sub
    paths=$(cat)

    [ -f .gitmodules ] || return 0
    [ -n "$paths" ] || return 0

    while IFS= read -r sub; do
        [ -n "$sub" ] || continue
        # ONLY `^sub/` — a file inside the submodule. A bare `^sub$` is the gitlink itself, which
        # means a pin bump, and a pin bump is not a boundary violation: ADR-0027 rule 5 requires the
        # super-repo to move pointers, and moving four at once is the normal shape of a cross-repo
        # change landing. Counting those as a span made this gate reject the very workflow its own
        # error message tells you to follow.
        if printf '%s\n' "$paths" | grep -q "^${sub}/"; then
            printf '%s\n' "$sub"
        fi
    done < <(git config -f .gitmodules --get-regexp '^submodule\..*\.path$' | awk '{print $2}')
}
