# shellcheck shell=bash
# GENERATED from governance canonical/agent-surfaces/ by scripts/gen-agent-surfaces.sh (ADR-0037).
# Do not edit this file. Edit the canonical source and regenerate; CI fails on drift.
# Reading a declaration out of a PR body. SPEC-0012 and SPEC-0013.
#
# Sourced, not executed. Both PR-body gates need the same answer to "what did the author actually
# declare", and the naive answer is wrong in a way that took two CI failures to see.
#
# A PR body is prose. It contains fenced code blocks, quoted examples, and documentation of the very
# syntax being parsed. `grep '^Scope:'` happily matches the example inside
#
#     ```
#     Scope: backend modules/policy/** **/*_test.go
#     ```
#
# and then enforces it — which is exactly what happened: a governance PR was rejected against a
# backend scope it had copied out of its own explanatory text.
#
# So a declaration is only a declaration when it is BOTH outside every fenced code block AND in the
# header, before the first Markdown heading. Anything after a `## ` is discussion, and discussion is
# where examples live.

# pr_declaration <key> <body-on-stdin> — print the declared value, or nothing.
pr_declaration() {
    local key=$1 line fenced=0

    while IFS= read -r line || [ -n "$line" ]; do
        # Fence toggling. ``` and ~~~ both, with or without a language tag.
        case "$line" in
            '```'*|'~~~'*) fenced=$((1 - fenced)); continue ;;
        esac
        [ "$fenced" -eq 0 ] || continue

        # The header ends at the first heading; past that, a match is an example.
        case "$line" in '#'*' '*) return 0 ;; esac

        case "$line" in
            "$key":*)
                line=${line#"$key":}
                # Trim surrounding whitespace, and the CR that arrives with a GitHub body.
                line=${line#"${line%%[![:space:]]*}"}
                line=${line%"${line##*[![:space:]]}"}
                printf '%s\n' "$line"
                return 0
                ;;
        esac
    done
}
